/* ============================================================
                JOBFIT-SCORE
Joao Gabriel Boaventura Marques e Silva | RM554874 | 2TDSB-2025
Leo Mota Lima                           | RM557851 | 2TDSB-2025
Lucas Leal das Chagas                   | RM551124 | 2TDSB-2025
============================================================ */

SET SERVEROUTPUT ON;
SET VERIFY OFF;

DROP TABLE vaga_habilidade CASCADE CONSTRAINTS;
DROP TABLE usuario_habilidade CASCADE CONSTRAINTS;
DROP TABLE candidaturas CASCADE CONSTRAINTS;
DROP TABLE cursos CASCADE CONSTRAINTS;
DROP TABLE habilidades CASCADE CONSTRAINTS;
DROP TABLE vagas CASCADE CONSTRAINTS;
DROP TABLE empresas CASCADE CONSTRAINTS;
DROP TABLE usuarios CASCADE CONSTRAINTS;
DROP TABLE auditoria_log CASCADE CONSTRAINTS;

CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    senha VARCHAR2(200) NOT NULL,
    refresh_token VARCHAR2(200),
    expira_refresh_token DATE
);

CREATE TABLE empresas (
    id_empresa NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL UNIQUE,
    cnpj VARCHAR2(14) NOT NULL UNIQUE,
    email VARCHAR2(100) UNIQUE NOT NULL,
    senha VARCHAR2(200) NOT NULL,
    refresh_token VARCHAR2(200),
    expira_refresh_token DATE
);

CREATE TABLE vagas (
    id_vaga NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(100) NOT NULL,
    empresa_id NUMBER NOT NULL,
    FOREIGN KEY (empresa_id) REFERENCES empresas(id_empresa)
);

CREATE TABLE habilidades (
    id_habilidade NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE usuario_habilidade (
    id_usuario_habilidade NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    habilidade_id NUMBER NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (habilidade_id) REFERENCES habilidades(id_habilidade) ON DELETE CASCADE,
    CONSTRAINT unq_usuario_habilidade UNIQUE (usuario_id, habilidade_id)
);

CREATE TABLE cursos (
    id_curso NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(150) NOT NULL,
    instituicao VARCHAR2(150),
    carga_horaria NUMBER,
    usuario_id NUMBER NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE candidaturas (
    id_candidatura NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    vaga_id NUMBER NOT NULL,
    data_candidatura DATE DEFAULT sysdate,
    status VARCHAR2(50) DEFAULT 'Em Análise',
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    FOREIGN KEY (vaga_id) REFERENCES vagas(id_vaga) ON DELETE CASCADE,
    CONSTRAINT chk_status CHECK (status IN ('Em Análise', 'Triagem', 'Aprovado', 'Reprovado'))
);

CREATE TABLE vaga_habilidade (
    id_vaga_habilidade NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vaga_id NUMBER NOT NULL,
    habilidade_id NUMBER NOT NULL,
    FOREIGN KEY (vaga_id) REFERENCES vagas(id_vaga) ON DELETE CASCADE,
    FOREIGN KEY (habilidade_id) REFERENCES habilidades(id_habilidade) ON DELETE CASCADE,
    CONSTRAINT unq_vaga_habilidade UNIQUE (vaga_id, habilidade_id)
);

CREATE TABLE auditoria_log (
    id_auditoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_tabela VARCHAR2(50) NOT NULL,
    operacao VARCHAR2(10) NOT NULL,
    registro_id NUMBER,
    usuario_banco VARCHAR2(50) DEFAULT USER,
    data_operacao DATE DEFAULT SYSDATE,
    detalhe VARCHAR2(4000)
);


/*=====================
Triggers
=======================*/

CREATE OR REPLACE TRIGGER trg_audit_usuarios
AFTER INSERT OR UPDATE OR DELETE ON usuarios
FOR EACH ROW
DECLARE
    v_operacao VARCHAR2(10);
    v_detalhe VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_operacao := 'INSERT';
        v_detalhe := 'Novo usuário: ' || :NEW.nome;
    ELSIF UPDATING THEN
        v_operacao := 'UPDATE';
        v_detalhe := 'Usuário atualizado: ' || :NEW.nome;
    ELSE
        v_operacao := 'DELETE';
        v_detalhe := 'Usuário removido: ' || :OLD.nome;
    END IF;

    INSERT INTO auditoria_log (nome_tabela, operacao, registro_id, detalhe)
    VALUES ('USUARIOS', v_operacao, NVL(:NEW.id_usuario, :OLD.id_usuario),
        v_detalhe);
END;
/

CREATE OR REPLACE TRIGGER trg_audit_empresas
AFTER INSERT OR UPDATE OR DELETE ON empresas
FOR EACH ROW
DECLARE
    v_operacao VARCHAR2(10);
    v_detalhe VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_operacao := 'INSERT';
        v_detalhe := 'Nova empresa: ' || :NEW.nome;
    ELSIF UPDATING THEN
        v_operacao := 'UPDATE';
        v_detalhe := 'Empresa atualizada: ' || :NEW.nome;
    ELSE
        v_operacao := 'DELETE';
        v_detalhe := 'Empresa removida: ' || :OLD.nome;
    END IF;

    INSERT INTO auditoria_log (nome_tabela, operacao, registro_id, detalhe)
    VALUES (
        'EMPRESAS',
        v_operacao,
        NVL(:NEW.id_empresa, :OLD.id_empresa),
        v_detalhe
    );
END;
/

CREATE OR REPLACE TRIGGER trg_audit_vagas
AFTER INSERT OR UPDATE OR DELETE ON vagas
FOR EACH ROW
DECLARE
    v_operacao VARCHAR2(10);
    v_detalhe VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_operacao := 'INSERT';
        v_detalhe := 'Nova vaga: ' || :NEW.titulo;
    ELSIF UPDATING THEN
        v_operacao := 'UPDATE';
        v_detalhe := 'Vaga atualizada: ' || :NEW.titulo;
    ELSE
        v_operacao := 'DELETE';
        v_detalhe := 'Vaga removida: ' || :OLD.titulo;
    END IF;

    INSERT INTO auditoria_log (nome_tabela, operacao, registro_id, detalhe)
    VALUES (
        'VAGAS',
        v_operacao,
        NVL(:NEW.id_vaga, :OLD.id_vaga),
        v_detalhe
    );
END;
/

CREATE OR REPLACE TRIGGER trg_audit_habilidades
AFTER INSERT OR UPDATE OR DELETE ON habilidades
FOR EACH ROW
DECLARE
    v_operacao VARCHAR2(10);
    v_detalhe VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_operacao := 'INSERT';
        v_detalhe := 'Nova habilidade: ' || :NEW.nome;
    ELSIF UPDATING THEN
        v_operacao := 'UPDATE';
        v_detalhe := 'Habilidade atualizada: ' || :NEW.nome;
    ELSE
        v_operacao := 'DELETE';
        v_detalhe := 'Habilidade removida: ' || :OLD.nome;
    END IF;

    INSERT INTO auditoria_log (nome_tabela, operacao, registro_id, detalhe)
    VALUES (
        'HABILIDADES',
        v_operacao,
        NVL(:NEW.id_habilidade, :OLD.id_habilidade),
        v_detalhe
    );
END;
/

CREATE OR REPLACE TRIGGER trg_audit_usuario_habilidade
AFTER INSERT OR UPDATE OR DELETE ON usuario_habilidade
FOR EACH ROW
DECLARE
    v_operacao VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_operacao := 'INSERT';
    ELSIF UPDATING THEN
        v_operacao := 'UPDATE';
    ELSE
        v_operacao := 'DELETE';
    END IF;

    INSERT INTO auditoria_log (nome_tabela, operacao, registro_id, detalhe)
    VALUES (
        'USUARIO_HABILIDADE',
        v_operacao,
        NVL(:NEW.id_usuario_habilidade, :OLD.id_usuario_habilidade),
        'Usuário ' || NVL(:NEW.usuario_id, :OLD.usuario_id) ||
        ' ↔ Habilidade ' || NVL(:NEW.habilidade_id, :OLD.habilidade_id)
    );
END;
/

CREATE OR REPLACE TRIGGER trg_audit_cursos
AFTER INSERT OR UPDATE OR DELETE ON cursos
FOR EACH ROW
DECLARE
    v_operacao VARCHAR2(10);
    v_detalhe VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_operacao := 'INSERT';
        v_detalhe := 'Curso adicionado: ' || :NEW.nome;
    ELSIF UPDATING THEN
        v_operacao := 'UPDATE';
        v_detalhe := 'Curso atualizado: ' || :NEW.nome;
    ELSE
        v_operacao := 'DELETE';
        v_detalhe := 'Curso removido: ' || :OLD.nome;
    END IF;

    INSERT INTO auditoria_log (nome_tabela, operacao, registro_id, detalhe)
    VALUES (
        'CURSOS',
        v_operacao,
        NVL(:NEW.id_curso, :OLD.id_curso),
        v_detalhe
    );
END;
/

CREATE OR REPLACE TRIGGER trg_audit_candidaturas
AFTER INSERT OR UPDATE OR DELETE ON candidaturas
FOR EACH ROW
DECLARE
    v_operacao VARCHAR2(10);
    v_detalhe VARCHAR2(4000);
BEGIN
    IF INSERTING THEN
        v_operacao := 'INSERT';
        v_detalhe := 'Nova candidatura de usuário ' || :NEW.usuario_id;
    ELSIF UPDATING THEN
        v_operacao := 'UPDATE';
        v_detalhe := 'Status atualizado para ' || :NEW.status;
    ELSE
        v_operacao := 'DELETE';
        v_detalhe := 'Candidatura removida de usuário ' || :OLD.usuario_id;
    END IF;

    INSERT INTO auditoria_log (nome_tabela, operacao, registro_id, detalhe)
    VALUES (
        'CANDIDATURAS',
        v_operacao,
        NVL(:NEW.id_candidatura, :OLD.id_candidatura),
        v_detalhe
    );
END;
/

CREATE OR REPLACE TRIGGER trg_audit_vaga_habilidade
AFTER INSERT OR UPDATE OR DELETE ON vaga_habilidade
FOR EACH ROW
DECLARE
    v_operacao VARCHAR2(10);
BEGIN
    IF INSERTING THEN
        v_operacao := 'INSERT';
    ELSIF UPDATING THEN
        v_operacao := 'UPDATE';
    ELSE
        v_operacao := 'DELETE';
    END IF;

    INSERT INTO auditoria_log (nome_tabela, operacao, registro_id, detalhe)
    VALUES (
        'VAGA_HABILIDADE',
        v_operacao,
        NVL(:NEW.id_vaga_habilidade, :OLD.id_vaga_habilidade),
        'Vaga ' || NVL(:NEW.vaga_id, :OLD.vaga_id) ||
        ' ↔ Habilidade ' || NVL(:NEW.habilidade_id, :OLD.habilidade_id)
    );
END;
/


/*============================================
PACKAGE DE PROCEDURES DE INSERÇÃO DE DADOS
==============================================*/

CREATE OR REPLACE PACKAGE pkg_insertDados AS
    PROCEDURE sp_inserir_usuario(p_nome IN VARCHAR2, p_email IN VARCHAR2, p_senha IN VARCHAR2, p_id_usuario OUT NUMBER);

    PROCEDURE sp_inserir_empresa(p_nome IN VARCHAR2, p_cnpj IN VARCHAR2, p_email IN VARCHAR2, p_senha IN VARCHAR2, p_id_empresa OUT NUMBER);

    PROCEDURE sp_inserir_vaga(p_titulo IN VARCHAR2, p_empresa_id IN NUMBER, p_id_vaga OUT NUMBER);
    PROCEDURE sp_inserir_vaga_habilidade(p_vaga_id IN NUMBER, p_habilidade_id IN NUMBER);

    PROCEDURE sp_inserir_habilidade(p_nome IN VARCHAR2, p_id_habilidade OUT NUMBER);
    PROCEDURE sp_inserir_usuario_habilidade(p_usuario_id IN NUMBER, p_habilidade_id IN NUMBER);

    PROCEDURE sp_inserir_curso(p_nome IN VARCHAR2, p_instituicao IN VARCHAR2, p_carga_horaria IN NUMBER, p_usuario_id IN NUMBER, p_id_curso OUT NUMBER);

    PROCEDURE sp_inserir_candidatura(p_usuario_id IN NUMBER, p_vaga_id IN NUMBER, p_id_candidatura OUT NUMBER);
END pkg_insertDados;
/

CREATE OR REPLACE PACKAGE BODY pkg_insertDados AS

    PROCEDURE sp_inserir_usuario(p_nome IN VARCHAR2, p_email IN VARCHAR2, p_senha IN VARCHAR2, p_id_usuario OUT NUMBER) AS
    BEGIN
        INSERT INTO usuarios (nome, email, senha)
        VALUES (p_nome, p_email, p_senha)
        RETURNING id_usuario INTO p_id_usuario;
        COMMIT;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20001, 'Email já cadastrado');
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END;

    PROCEDURE sp_inserir_empresa(p_nome IN VARCHAR2, p_cnpj IN VARCHAR2, p_email IN VARCHAR2, p_senha IN VARCHAR2, p_id_empresa OUT NUMBER) AS
    BEGIN
        INSERT INTO empresas (nome, cnpj, email, senha)
        VALUES (p_nome, p_cnpj, p_email, p_senha)
        RETURNING id_empresa INTO p_id_empresa;
        COMMIT;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20002, 'Nome, CNPJ ou Email já cadastrado');
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END;

    PROCEDURE sp_inserir_vaga(p_titulo IN VARCHAR2, p_empresa_id IN NUMBER, p_id_vaga OUT NUMBER) AS
    BEGIN
        INSERT INTO vagas (titulo, empresa_id)
        VALUES (p_titulo, p_empresa_id)
        RETURNING id_vaga INTO p_id_vaga;
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END;

    PROCEDURE sp_inserir_vaga_habilidade(p_vaga_id IN NUMBER, p_habilidade_id IN NUMBER) AS
    BEGIN
        INSERT INTO vaga_habilidade (vaga_id, habilidade_id)
        VALUES (p_vaga_id, p_habilidade_id);
        COMMIT;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20005, 'Vaga já possui esta habilidade');
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END;

    PROCEDURE sp_inserir_habilidade(p_nome IN VARCHAR2, p_id_habilidade OUT NUMBER) AS
    BEGIN
        INSERT INTO habilidades (nome)
        VALUES (p_nome)
        RETURNING id_habilidade INTO p_id_habilidade;
        COMMIT;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20003, 'Habilidade já cadastrada');
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END;

    PROCEDURE sp_inserir_usuario_habilidade(p_usuario_id IN NUMBER, p_habilidade_id IN NUMBER) AS
    BEGIN
        INSERT INTO usuario_habilidade (usuario_id, habilidade_id)
        VALUES (p_usuario_id, p_habilidade_id);
        COMMIT;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20004, 'Usuário já possui esta habilidade');
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END;

    PROCEDURE sp_inserir_curso(p_nome IN VARCHAR2, p_instituicao IN VARCHAR2, p_carga_horaria IN NUMBER, p_usuario_id IN NUMBER, p_id_curso OUT NUMBER) AS
    BEGIN
        INSERT INTO cursos (nome, instituicao, carga_horaria, usuario_id)
        VALUES (p_nome, p_instituicao, p_carga_horaria, p_usuario_id)
        RETURNING id_curso INTO p_id_curso;
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END;

    PROCEDURE sp_inserir_candidatura(p_usuario_id IN NUMBER, p_vaga_id IN NUMBER, p_id_candidatura OUT NUMBER) AS
    BEGIN
        INSERT INTO candidaturas (usuario_id, vaga_id)
        VALUES (p_usuario_id, p_vaga_id)
        RETURNING id_candidatura INTO p_id_candidatura;
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END;

END pkg_insertDados;
/

/*===================
INSERÇÃO DE DADOS
===================*/


DECLARE
    v_id NUMBER;
BEGIN
    pkg_insertDados.sp_inserir_usuario('Ana Paula Santos', 'ana.santos@email.com', 'ana123', v_id);
    pkg_insertDados.sp_inserir_usuario('Carlos Eduardo Lima', 'carlos.lima@email.com', 'carlos123', v_id);
    pkg_insertDados.sp_inserir_usuario('Mariana Costa Silva', 'mariana.costa@email.com', 'mariana123', v_id);
    pkg_insertDados.sp_inserir_usuario('Ricardo Almeida', 'ricardo.almeida@email.com', 'ricardo123', v_id);
    pkg_insertDados.sp_inserir_usuario('Juliana Ferreira', 'juliana.ferreira@email.com', 'juliana123', v_id);
    pkg_insertDados.sp_inserir_usuario('Fernando Oliveira', 'fernando.oliveira@email.com', 'fernando123', v_id);
    pkg_insertDados.sp_inserir_usuario('Beatriz Rodrigues', 'beatriz.rodrigues@email.com', 'beatriz123', v_id);
    pkg_insertDados.sp_inserir_usuario('Paulo Henrique Souza', 'paulo.souza@email.com', 'paulo123', v_id);
    pkg_insertDados.sp_inserir_usuario('Camila Martins', 'camila.martins@email.com', 'camila123', v_id);
    pkg_insertDados.sp_inserir_usuario('Gabriel Pereira', 'gabriel.pereira@email.com', 'gabriel123', v_id);
    DBMS_OUTPUT.PUT_LINE('Usuários inseridos com sucesso!');
END;
/

DECLARE
    v_id NUMBER;
BEGIN
    pkg_insertDados.sp_inserir_empresa('Tech Solutions Brasil', '12345678000190', 'contato@techsolutions.com', 'tech123', v_id);
    pkg_insertDados.sp_inserir_empresa('Inovação Digital Ltda', '98765432000145', 'contato@inovacaodigital.com', 'inovacao23', v_id);
    pkg_insertDados.sp_inserir_empresa('Consultoria TI Express', '11223344000156', 'contato@consultorati.com', 'consultoriaexp05', v_id);
    pkg_insertDados.sp_inserir_empresa('Desenvolve Software SA', '55667788000198', 'contato@desenvolvesoftware.com', 'devsoftware4', v_id);
    pkg_insertDados.sp_inserir_empresa('Cloud Computing Brasil', '99887766000132', 'contato@cloudcomputing.com', 'cloudcomp647', v_id);
    pkg_insertDados.sp_inserir_empresa('Data Science Corp', '44556677000178', 'contato@datascience.com', 'dtscience69', v_id);
    pkg_insertDados.sp_inserir_empresa('Agile Developers', '33221100000165', 'contato@agiledev.com', 'agildev456', v_id);
    pkg_insertDados.sp_inserir_empresa('Web Solutions Pro', '77889900000123', 'contato@websolutions.com', 'websol5467', v_id);
    pkg_insertDados.sp_inserir_empresa('Mobile Apps Brasil', '66554433000187', 'contato@mobileapps.com', 'mobileapp012', v_id);
    pkg_insertDados.sp_inserir_empresa('Cyber Security Tech', '22334455000141', 'contato@cybersecurity.com', 'cibersecurity40921', v_id);
END;
/

DECLARE
    v_id NUMBER;
BEGIN
    pkg_insertDados.sp_inserir_habilidade('Java', v_id);
    pkg_insertDados.sp_inserir_habilidade('Python', v_id);
    pkg_insertDados.sp_inserir_habilidade('JavaScript', v_id);
    pkg_insertDados.sp_inserir_habilidade('SQL', v_id);
    pkg_insertDados.sp_inserir_habilidade('React', v_id);
    pkg_insertDados.sp_inserir_habilidade('Node.js', v_id);
    pkg_insertDados.sp_inserir_habilidade('Docker', v_id);
    pkg_insertDados.sp_inserir_habilidade('Kubernetes', v_id);
    pkg_insertDados.sp_inserir_habilidade('AWS', v_id);
    pkg_insertDados.sp_inserir_habilidade('Git', v_id);
END;
/


DECLARE
    v_id NUMBER;
BEGIN
    pkg_insertDados.sp_inserir_vaga('Desenvolvedor Java Pleno', 1, v_id);
    pkg_insertDados.sp_inserir_vaga('Analista Python Sênior', 2, v_id);
    pkg_insertDados.sp_inserir_vaga('Desenvolvedor Full Stack', 3, v_id);
    pkg_insertDados.sp_inserir_vaga('Engenheiro de Dados', 4, v_id);
    pkg_insertDados.sp_inserir_vaga('Arquiteto de Soluções Cloud', 5, v_id);
    pkg_insertDados.sp_inserir_vaga('Cientista de Dados', 6, v_id);
    pkg_insertDados.sp_inserir_vaga('Scrum Master', 7, v_id);
    pkg_insertDados.sp_inserir_vaga('Desenvolvedor Front-End React', 8, v_id);
    pkg_insertDados.sp_inserir_vaga('Desenvolvedor Mobile Android', 9, v_id);
    pkg_insertDados.sp_inserir_vaga('Analista de Segurança da Informação', 10, v_id);
END;
/

BEGIN
    pkg_insertDados.sp_inserir_usuario_habilidade(1, 1);
    pkg_insertDados.sp_inserir_usuario_habilidade(2, 2);
    pkg_insertDados.sp_inserir_usuario_habilidade(3, 3);
    pkg_insertDados.sp_inserir_usuario_habilidade(4, 4);
    pkg_insertDados.sp_inserir_usuario_habilidade(5, 5);
    pkg_insertDados.sp_inserir_usuario_habilidade(6, 6);
    pkg_insertDados.sp_inserir_usuario_habilidade(7, 7);
    pkg_insertDados.sp_inserir_usuario_habilidade(8, 8);
    pkg_insertDados.sp_inserir_usuario_habilidade(9, 9);
    pkg_insertDados.sp_inserir_usuario_habilidade(10, 10);
END;
/


DECLARE
    v_id NUMBER;
BEGIN
    pkg_insertDados.sp_inserir_curso('Java Avançado', 'Alura', 40, 1, v_id);
    pkg_insertDados.sp_inserir_curso('Python para Data Science', 'Coursera', 60, 2, v_id);
    pkg_insertDados.sp_inserir_curso('React do Zero ao Avançado', 'Udemy', 50, 3, v_id);
    pkg_insertDados.sp_inserir_curso('Banco de Dados Oracle', 'FIAP', 80, 4, v_id);
    pkg_insertDados.sp_inserir_curso('AWS Solutions Architect', 'AWS Training', 120, 5, v_id);
    pkg_insertDados.sp_inserir_curso('Docker e Kubernetes', 'LinuxTips', 40, 6, v_id);
    pkg_insertDados.sp_inserir_curso('JavaScript Moderno', 'Rocketseat', 35, 7, v_id);
    pkg_insertDados.sp_inserir_curso('Node.js Completo', 'Udemy', 45, 8, v_id);
    pkg_insertDados.sp_inserir_curso('Scrum Master Certification', 'Scrum.org', 16, 9, v_id);
    pkg_insertDados.sp_inserir_curso('Segurança da Informação', 'Descomplica', 60, 10, v_id);
END;
/

BEGIN
    pkg_insertDados.sp_inserir_vaga_habilidade(1, 1);
    pkg_insertDados.sp_inserir_vaga_habilidade(2, 2);
    pkg_insertDados.sp_inserir_vaga_habilidade(3, 3);
    pkg_insertDados.sp_inserir_vaga_habilidade(4, 4);
    pkg_insertDados.sp_inserir_vaga_habilidade(5, 5);
    pkg_insertDados.sp_inserir_vaga_habilidade(6, 6);
    pkg_insertDados.sp_inserir_vaga_habilidade(7, 7);
    pkg_insertDados.sp_inserir_vaga_habilidade(8, 8);
    pkg_insertDados.sp_inserir_vaga_habilidade(9, 9);
    pkg_insertDados.sp_inserir_vaga_habilidade(10, 10);
END;
/

DECLARE
    v_id NUMBER;
BEGIN
    pkg_insertDados.sp_inserir_candidatura(1, 1, v_id);
    pkg_insertDados.sp_inserir_candidatura(2, 2, v_id);
    pkg_insertDados.sp_inserir_candidatura(3, 3, v_id);
    pkg_insertDados.sp_inserir_candidatura(4, 4, v_id);
    pkg_insertDados.sp_inserir_candidatura(5, 5, v_id);
    pkg_insertDados.sp_inserir_candidatura(6, 6, v_id);
    pkg_insertDados.sp_inserir_candidatura(7, 7, v_id);
    pkg_insertDados.sp_inserir_candidatura(8, 8, v_id);
    pkg_insertDados.sp_inserir_candidatura(9, 9, v_id);
    pkg_insertDados.sp_inserir_candidatura(10, 10, v_id);
END;
/


/*======================
PACKAGE DE FUNÇÕES
=======================*/

CREATE OR REPLACE PACKAGE pkg_jobfit_funcoes AS
    FUNCTION fn_usuario_para_json(p_usuario_id IN NUMBER) RETURN CLOB;
    FUNCTION fn_validar_e_calcular(
        p_email       IN VARCHAR2,
        p_cpf         IN VARCHAR2,
        p_usuario_id  IN NUMBER,
        p_vaga_id     IN NUMBER
    ) RETURN CLOB;
END pkg_jobfit_funcoes;
/

CREATE OR REPLACE PACKAGE BODY pkg_jobfit_funcoes AS
    FUNCTION fn_usuario_para_json(p_usuario_id IN NUMBER)
    RETURN CLOB
    AS
        v_json CLOB := EMPTY_CLOB();
        v_nome VARCHAR2(100);
        v_email VARCHAR2(100);
        v_usuario_existe NUMBER := 0;
        
        -- Cursor para buscar habilidades do usuário
        CURSOR c_habilidade IS SELECT h.nome
            FROM usuario_habilidade uh 
            JOIN habilidades h ON h.id_habilidade = uh.habilidade_id
            WHERE uh.usuario_id = p_usuario_id;
        
        CURSOR c_cursos IS SELECT nome, instituicao, NVL(carga_horaria, 0) carga
            FROM cursos WHERE usuario_id = p_usuario_id;
        
        v_first BOOLEAN; -- Controle para inserção de vírgulas no JSON
        
    BEGIN
        IF p_usuario_id IS NULL THEN
            RETURN '{"error":"Parâmetro p_usuario_id não pode ser nulo"}';
        END IF;
        
        SELECT COUNT(*) INTO v_usuario_existe
        FROM usuarios
        WHERE id_usuario = p_usuario_id;
        
        IF v_usuario_existe = 0 THEN
            RETURN '{"error":"Usuário com ID ' || p_usuario_id || ' não encontrado"}';
        END IF;
        
        SELECT nome, email INTO v_nome, v_email
        FROM usuarios
        WHERE id_usuario = p_usuario_id;
        
        v_json := '{';
        v_json := v_json || '"id_usuario":' || TO_CHAR(p_usuario_id) || ',';
        v_json := v_json || '"nome":"' || REPLACE(v_nome, '"', '\"') || '",';
        v_json := v_json || '"email":"' || REPLACE(v_email, '"', '\"') || '",';
        
        ---
        
        v_json := v_json || '"habilidades":[';
        v_first := TRUE;
        
        FOR r IN c_habilidade LOOP
            IF NOT v_first THEN
                v_json := v_json || ',';
            END IF;
            v_json := v_json || '"' || REPLACE(r.nome, '"', '\"') || '"';
            v_first := FALSE;
        END LOOP;
        
        v_json := v_json || '],';
        
        ---
        
        v_json := v_json || '"cursos":[';
        v_first := TRUE;
        
        FOR r IN c_cursos LOOP
            IF NOT v_first THEN
                v_json := v_json || ',';
            END IF;
            v_json := v_json || '{'
                || '"nome":"' || REPLACE(r.nome, '"', '\"') || '",'
                || '"instituicao":"' || REPLACE(NVL(r.instituicao, 'N/A'), '"', '\"') || '",'
                || '"carga_horaria":' || TO_CHAR(r.carga)
                || '}';
            v_first := FALSE;
        END LOOP;
        
        v_json := v_json || ']';
        v_json := v_json || '}';
        
        RETURN v_json;
        
    EXCEPTION
        WHEN TOO_MANY_ROWS THEN
            RETURN '{"error":"Múltiplos usuários encontrados com ID ' || p_usuario_id || '"}';
        WHEN NO_DATA_FOUND THEN
            RETURN '{"error":"Dados não encontrados para o usuário ID ' || p_usuario_id || '"}';
        WHEN VALUE_ERROR THEN
            RETURN '{"error":"Erro ao processar dados - valor inválido"}';
        WHEN OTHERS THEN
            RETURN '{"error":"Erro inesperado: ' || SQLERRM || '"}';
    END fn_usuario_para_json;

    ------

    FUNCTION fn_validar_e_calcular (
        p_email IN VARCHAR2,
        p_cpf   IN VARCHAR2,
        p_usuario_id IN NUMBER,
        p_vaga_id IN NUMBER
    ) RETURN CLOB IS
        v_resultado CLOB := EMPTY_CLOB();
        v_email_valido BOOLEAN := FALSE;
        v_cpf_valido BOOLEAN := FALSE;
        v_total_habilidades_vaga NUMBER := 0;
        v_habilidades_correspondentes NUMBER := 0;
        v_score NUMBER := 0;
    BEGIN
        IF REGEXP_LIKE(p_email, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
            v_email_valido := TRUE;
        END IF;

        IF REGEXP_LIKE(p_cpf, '^[0-9]{3}\.?[0-9]{3}\.?[0-9]{3}-?[0-9]{2}$') THEN
            v_cpf_valido := TRUE;
        END IF;

        SELECT NVL(COUNT(*),0) INTO v_total_habilidades_vaga
        FROM vaga_habilidade
        WHERE vaga_id = p_vaga_id;

        SELECT NVL(COUNT(*),0) INTO v_habilidades_correspondentes
        FROM usuario_habilidade uh
        JOIN vaga_habilidade vh 
            ON uh.habilidade_id = vh.habilidade_id
        WHERE uh.usuario_id = p_usuario_id
          AND vh.vaga_id = p_vaga_id;

        IF v_total_habilidades_vaga > 0 THEN
            v_score := ROUND((v_habilidades_correspondentes / v_total_habilidades_vaga) * 100, 2);
        ELSE
            v_score := 0;
        END IF;

        v_resultado := '{"email_valido": ' || CASE WHEN v_email_valido THEN 'true' ELSE 'false' END ||
                       ', "cpf_valido": ' || CASE WHEN v_cpf_valido THEN 'true' ELSE 'false' END ||
                       ', "compatibilidade": ' || v_score ||
                       ', "mensagem": "Validação e cálculo realizados com sucesso"}';
        RETURN v_resultado;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN '{"erro": "Usuário ou vaga inexistente."}';
        WHEN ZERO_DIVIDE THEN
            RETURN '{"erro": "Vaga sem habilidades cadastradas para cálculo."}';
        WHEN OTHERS THEN
            RETURN '{"erro": "Falha ao processar os dados: ' || SQLERRM || '"}';
    END fn_validar_e_calcular;

END pkg_jobfit_funcoes;
/


SELECT pkg_jobfit_funcoes.fn_usuario_para_json(1) AS json_resultado FROM dual;
SELECT pkg_jobfit_funcoes.fn_usuario_para_json(999) AS json_resultado FROM dual;

SELECT pkg_jobfit_funcoes.fn_validar_e_calcular('ana.santos@email.com', '123.456.789-00', 1, 1) FROM dual;
SELECT pkg_jobfit_funcoes.fn_validar_e_calcular('carlos.lima@email.com', '987.654.321-00', 2, 1) FROM dual;


/*=================================
procedure para exportar o dataset
===================================*/
CREATE OR REPLACE PROCEDURE exportar_tabela_json(p_tabela IN VARCHAR2) IS
    v_sql        VARCHAR2(4000);
    v_cols       VARCHAR2(4000);
    v_json       CLOB;
    v_nome_arquivo VARCHAR2(200);
BEGIN
SELECT LISTAGG(
        CASE WHEN ROWNUM = 1 THEN 
            '''_id'' VALUE ' || column_name
            ELSE '''' || column_name || ''' VALUE ' || column_name
        END, ', '
    ) WITHIN GROUP (ORDER BY column_id)
INTO v_cols
FROM user_tab_columns
WHERE table_name = UPPER(p_tabela);

    v_sql := 'SELECT JSON_ARRAYAGG(JSON_OBJECT(' || v_cols || ' RETURNING CLOB)) FROM ' || p_tabela;
    EXECUTE IMMEDIATE v_sql INTO v_json;

    v_nome_arquivo := LOWER(p_tabela) || '.json';
    DBMS_OUTPUT.PUT_LINE(v_json);

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro ao exportar tabela ' || p_tabela || ': ' || SQLERRM);
END;
/


/* 
Para exportar as tabelas corretamente 
execute selecione essa sequência de SET
*/
SET SQLPROMPT '' 
SET FEEDBACK OFF 
SET HEADING OFF 
SET VERIFY OFF 
SET ECHO OFF 
SET TERMOUT OFF
SET SERVEROUTPUT ON

SPOOL vaga_habilidade.json
EXEC exportar_tabela_json('vaga_habilidade');
SPOOL OFF;

SPOOL usuario_habilidade.json
EXEC exportar_tabela_json('usuario_habilidade');
SPOOL OFF;

SPOOL candidaturas.json
EXEC exportar_tabela_json('candidaturas');
SPOOL OFF;

SPOOL cursos.json
EXEC exportar_tabela_json('cursos');
SPOOL OFF;

SPOOL habilidades.json
EXEC exportar_tabela_json('habilidades');
SPOOL OFF;

SPOOL vagas.json
EXEC exportar_tabela_json('vagas');
SPOOL OFF;

SPOOL empresas.json
EXEC exportar_tabela_json('empresas');
SPOOL OFF;

SPOOL usuarios.json
EXEC exportar_tabela_json('usuarios');
SPOOL OFF;

-- PARA O OUTPUT VOLTAR AO NORMAL, APENAS RECONECTE A SUA CONTA
